version: "3"

services:
  nextjs:
    container_name: MDGround3-service
    ports:
      - "3600:3600"
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app

  mysql:
    container_name: MDGround3-db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: md1234
      MYSQL_DATABASE: md3
    restart: always
    ports:
      - "33068:3306"
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_bin"
      ]

  adminer:
    container_name: MDGround3-adminer
    image: adminer
    restart: always
    ports:
      - 8098:8080
  
  redis:
    container_name: MDGround3-redis
    image: redis:latest
    ports:
      - "63791:6379"
    restart: always
    command: redis-server